export { default as Example } from './Example/Example';
export { default as Startup } from './Startup/Startup';
export { Splash } from './Splash';
export { Login } from './Login';
export { Home } from './Home';
export { Panchanga } from './Panchanga';
export { HistoryScreen } from './History';
export { GuruDetailScreen } from './GuruDetail';
export { GalleryScreen, AlbumDetailScreen } from './Gallery';
export { ArtefactsScreen, ArtefactDetailScreen } from './Artefacts';
export { RoomBookingScreen } from './RoomBooking';
export { SevasScreen, DevoteeFormScreen } from './Sevas';
